// Voxel engine: MagicaVoxel .vox parser + software renderer.
// Renders voxel models as chunky pixel art. No dependencies, no WebGL.
//
// Character assets (player + NPCs) are generated by tools/gen_models.py —
// adult-proportioned OSRS-style voxel characters. Regenerate and re-copy
// into wwwroot/assets when adding or restyling characters.
//
// API:
//   voxel.initPreview(canvasId, modelUrl)  — spinning drag-to-rotate preview
//   voxel.destroyPreview(canvasId)         — stop loop, detach listeners
//   voxel.renderIcon(modelUrl, size)       — Promise<dataURL> static 3/4-view
//                                            icon, cached per url+size
(function () {
    'use strict';

    const TILT = 0.3;            // isometric-ish downward tilt
    const SPIN_SPEED = 0.008;    // rad/frame idle auto-spin (~28s/rev)
    const DRAG_SPEED = 0.02;     // rad per dragged px
    const RESUME_MS = 2000;      // hold still after drag before spinning again
    const SHADES = 6;            // quantized depth-shading levels
    // Rig parts: color-index band per part (matches tools/gen_models.py).
    // Legacy (NPCs): band 40, 6 parts — 0 torso, 1 head, 2 rArm, 3 lArm,
    // 4 rLeg, 5 lLeg. v2 (player): band 16, 12 parts — limbs split at
    // elbow/knee/ankle for chained FK + leg IK; indices 0-5 keep the legacy
    // meaning so attack poses target the (upper) weapon arm unchanged.
    const PART_BAND = 40;
    const P_RARM = 2, P_LARM = 3, P_RLEG = 4, P_LLEG = 5;
    // Per-file part decode overrides (band width, part count). Everything
    // else uses the legacy 40-wide / 6-part scheme.
    const VOX_OPTS = { 'assets/player.vox': { band: 16, parts: 12 } };

    // ── .vox parsing ─────────────────────────────────────────────────────────

    // MagicaVoxel default palette (used when a file has no RGBA chunk):
    // 216 descending {ff,cc,99,66,33,00} B-fastest combos, then r/g/b ramps + grays.
    function defaultPalette() {
        const p = [[0, 0, 0]];
        const v = [255, 204, 153, 102, 51, 0];
        for (const r of v) for (const g of v) for (const b of v) p.push([r, g, b]);
        const ramp = [238, 221, 187, 170, 136, 119, 85, 68, 34, 17];
        for (const e of ramp) p.push([e, 0, 0]);
        for (const e of ramp) p.push([0, e, 0]);
        for (const e of ramp) p.push([0, 0, e]);
        for (const e of ramp.slice(0, 9)) p.push([e, e, e]);
        return p;
    }

    // Parses the first model in a .vox file into { voxels: [{x,y,z,ci}], palette }.
    // MagicaVoxel is Z-up; converted here to renderer Y-up.
    function parseVox(buf) {
        const dv = new DataView(buf);
        const tag = i => String.fromCharCode(dv.getUint8(i), dv.getUint8(i + 1), dv.getUint8(i + 2), dv.getUint8(i + 3));
        if (tag(0) !== 'VOX ') throw new Error('not a .vox file');

        let voxels = null;
        let palette = null;
        let pos = 8;
        while (pos + 12 <= buf.byteLength) {
            const id = tag(pos);
            const contentSize = dv.getUint32(pos + 4, true);
            const childrenSize = dv.getUint32(pos + 8, true);
            const start = pos + 12;
            if (id === 'XYZI' && voxels === null) {
                const n = dv.getUint32(start, true);
                voxels = new Array(n);
                for (let i = 0; i < n; i++) {
                    const o = start + 4 + i * 4;
                    voxels[i] = {
                        x: dv.getUint8(o),
                        y: dv.getUint8(o + 2),      // vox z → renderer y (up)
                        z: dv.getUint8(o + 1),      // vox y → renderer z (depth)
                        ci: dv.getUint8(o + 3),
                    };
                }
            } else if (id === 'RGBA') {
                // Palette convention: XYZI color index i reads RGBA entry i-1.
                palette = [[0, 0, 0]];
                for (let i = 0; i < 255; i++) {
                    const o = start + i * 4;
                    palette.push([dv.getUint8(o), dv.getUint8(o + 1), dv.getUint8(o + 2)]);
                }
            }
            // Chunk layout: [content][children]. Descend into MAIN's children;
            // skip other chunks entirely (content + children).
            pos = id === 'MAIN' ? start + contentSize : start + contentSize + childrenSize;
        }
        if (!voxels) throw new Error('no XYZI chunk');
        return { voxels, palette: palette ?? defaultPalette() };
    }

    // ── Model prep (once per load) ────────────────────────────────────────────

    // Center on x/z, ground at y=0, drop fully-enclosed interior voxels, and
    // precompute quantized depth-shade fillStyle strings per used color.
    function prepModel(parsed, band = PART_BAND, maxPart = 5) {
        const vs = parsed.voxels;
        let minX = 1e9, maxX = -1e9, minY = 1e9, minZ = 1e9, maxZ = -1e9, maxY = -1e9;
        for (const v of vs) {
            if (v.x < minX) minX = v.x; if (v.x > maxX) maxX = v.x;
            if (v.y < minY) minY = v.y; if (v.y > maxY) maxY = v.y;
            if (v.z < minZ) minZ = v.z; if (v.z > maxZ) maxZ = v.z;
        }
        const cx = (minX + maxX) / 2, cz = (minZ + maxZ) / 2;

        const occupied = new Set(vs.map(v => v.x + '|' + v.y + '|' + v.z));
        const surface = vs.filter(v =>
            !(occupied.has((v.x + 1) + '|' + v.y + '|' + v.z) &&
              occupied.has((v.x - 1) + '|' + v.y + '|' + v.z) &&
              occupied.has(v.x + '|' + (v.y + 1) + '|' + v.z) &&
              occupied.has(v.x + '|' + (v.y - 1) + '|' + v.z) &&
              occupied.has(v.x + '|' + v.y + '|' + (v.z + 1)) &&
              occupied.has(v.x + '|' + v.y + '|' + (v.z - 1))));

        let radius = 1;
        const voxels = surface.map(v => {
            const x = v.x - cx, z = v.z - cz;
            const r = Math.sqrt(x * x + z * z);
            if (r > radius) radius = r;
            // Rigged character models encode the body part in the color index
            // (bands of `band`, see tools/gen_models.py); unbanded models
            // land in part 0 (torso), which never poses.
            return { x, y: v.y - minY, z, ci: v.ci, part: Math.min(maxPart, ((v.ci - 1) / band) | 0) };
        });

        // shadeTable[ci][level] = fillStyle, level 0 (far/dark) .. SHADES-1 (near/bright)
        const shadeTable = {};
        for (const v of voxels) {
            if (shadeTable[v.ci]) continue;
            const [r, g, b] = parsed.palette[v.ci] ?? [255, 0, 255];
            const levels = new Array(SHADES);
            for (let l = 0; l < SHADES; l++) {
                const f = 0.65 + l * (0.5 / (SHADES - 1));
                levels[l] = `rgb(${Math.min(255, r * f) | 0},${Math.min(255, g * f) | 0},${Math.min(255, b * f) | 0})`;
            }
            shadeTable[v.ci] = levels;
        }

        return { voxels, height: maxY - minY + 1, radius, shadeTable, scratch: new Array(voxels.length) };
    }

    const modelCache = new Map(); // url → Promise<model>
    function loadModel(url) {
        if (!modelCache.has(url)) {
            const o = VOX_OPTS[url];
            modelCache.set(url, fetch(url)
                .then(r => { if (!r.ok) throw new Error(`${url}: HTTP ${r.status}`); return r.arrayBuffer(); })
                .then(buf => prepModel(parseVox(buf), o?.band, o ? o.parts - 1 : undefined)));
        }
        return modelCache.get(url);
    }

    // ── Rendering ─────────────────────────────────────────────────────────────

    // Draw one model at voxel size S with its ground-center at (cx, baseY).
    // pose (optional): array indexed by part → transform or null. A transform
    // is { pivot:[x,y,z], pitch, yaw, dz, dy, up }: pitch rotates the part
    // about its pivot (positive folds a hanging limb toward the model's
    // back), yaw sweeps it horizontally, dz/dy translate it. `up` chains to
    // the parent joint's transform — a foot voxel rotates about the ankle,
    // then the knee, then the hip, then takes the root offset (leg IK).
    function renderModel(ctx, model, angle, S, cx, baseY, pose) {
        const c = Math.cos(angle), sn = Math.sin(angle);
        const vs = model.voxels, out = model.scratch;
        if (pose) // precompute trig once per transform, following up-chains
            for (let t of pose)
                for (; t && t._cp === undefined; t = t.up) {
                    t._cp = Math.cos(t.pitch || 0); t._sp = Math.sin(t.pitch || 0);
                    t._cy = Math.cos(t.yaw || 0);   t._sy = Math.sin(t.yaw || 0);
                }
        for (let i = 0; i < vs.length; i++) {
            const v = vs[i];
            let x = v.x, y = v.y, z = v.z;
            for (let t = pose ? pose[v.part] : null; t; t = t.up) {
                if (t.pivot) {
                    const pv = t.pivot;
                    x -= pv[0]; y -= pv[1]; z -= pv[2];
                    if (t.pitch) { const y2 = y * t._cp - z * t._sp; z = y * t._sp + z * t._cp; y = y2; }
                    if (t.yaw)   { const x2 = x * t._cy - z * t._sy; z = x * t._sy + z * t._cy; x = x2; }
                    x += pv[0]; y += pv[1]; z += pv[2];
                }
                z += t.dz || 0; y += t.dy || 0;
            }
            const rx = x * c - z * sn;
            const rz = x * sn + z * c;
            out[i] = { rx, rz, y, ci: v.ci };
        }
        out.sort((a, b) => a.rz - b.rz); // far → near (painter's algorithm)

        const invSpan = 1 / (model.radius * 2 || 1);
        for (let i = 0; i < out.length; i++) {
            const v = out[i];
            let lvl = ((v.rz + model.radius) * invSpan * SHADES) | 0;
            if (lvl < 0) lvl = 0; else if (lvl >= SHADES) lvl = SHADES - 1;
            ctx.fillStyle = model.shadeTable[v.ci][lvl];
            ctx.fillRect((cx + v.rx * S) | 0, (baseY - v.y * S + v.rz * S * TILT) | 0, S + 1, S + 1);
        }
    }

    function render(ctx, W, H, model, angle) {
        ctx.clearRect(0, 0, W, H);
        // Auto-fit: horizontal must clear the rotation-swept diameter, vertical
        // the model height plus the tilt swing at top and bottom.
        const S = Math.max(1, Math.floor(Math.min(
            (W - 2) / (model.radius * 2 + 1),
            (H - 2) / (model.height + 1 + model.radius * 2 * TILT))));
        renderModel(ctx, model, angle, S, W / 2, (H + model.height * S) / 2);
    }

    // ── Interactive previews ──────────────────────────────────────────────────

    const previews = new Map(); // canvasId → state

    async function initPreview(canvasId, modelUrl) {
        destroyPreview(canvasId);
        let model;
        try { model = await loadModel(modelUrl); }
        catch (e) { console.warn('voxel: failed to load', modelUrl, e); return; }

        const canvas = document.getElementById(canvasId);
        if (!canvas) return; // component unmounted while the model was loading

        const st = {
            canvas,
            ctx: canvas.getContext('2d'),
            model,
            angle: 0.6,
            lastDrawn: NaN,
            dragging: false,
            dragX: 0,
            dragAngle: 0,
            resumeAt: 0,
            raf: 0,
        };

        st.onDown = e => {
            e.preventDefault();
            e.stopPropagation();
            st.dragging = true;
            st.dragX = e.clientX;
            st.dragAngle = st.angle;
            canvas.setPointerCapture(e.pointerId);
        };
        st.onMove = e => {
            if (st.dragging) st.angle = st.dragAngle + (e.clientX - st.dragX) * DRAG_SPEED;
        };
        st.onUp = () => {
            st.dragging = false;
            st.resumeAt = performance.now() + RESUME_MS;
        };
        canvas.addEventListener('pointerdown', st.onDown);
        canvas.addEventListener('pointermove', st.onMove);
        canvas.addEventListener('pointerup', st.onUp);
        canvas.addEventListener('pointercancel', st.onUp);

        const loop = () => {
            if (!st.dragging && performance.now() >= st.resumeAt) st.angle += SPIN_SPEED;
            if (st.angle !== st.lastDrawn) {
                render(st.ctx, canvas.width, canvas.height, st.model, st.angle);
                st.lastDrawn = st.angle;
            }
            st.raf = requestAnimationFrame(loop);
        };
        st.raf = requestAnimationFrame(loop);
        previews.set(canvasId, st);
    }

    function destroyPreview(canvasId) {
        const st = previews.get(canvasId);
        if (!st) return;
        cancelAnimationFrame(st.raf);
        st.canvas.removeEventListener('pointerdown', st.onDown);
        st.canvas.removeEventListener('pointermove', st.onMove);
        st.canvas.removeEventListener('pointerup', st.onUp);
        st.canvas.removeEventListener('pointercancel', st.onUp);
        previews.delete(canvasId);
    }

    // ── Static icons ──────────────────────────────────────────────────────────

    const iconCache = new Map(); // url|size → Promise<dataURL>

    function renderIcon(modelUrl, size) {
        const key = modelUrl + '|' + size;
        if (!iconCache.has(key)) {
            iconCache.set(key, loadModel(modelUrl).then(model => {
                const c = document.createElement('canvas');
                c.width = size; c.height = size;
                render(c.getContext('2d'), size, size, model, Math.PI / 5); // fixed 3/4 view
                return c.toDataURL();
            }));
        }
        return iconCache.get(key);
    }

    // Item ids that have a model at assets/items/<id>.vox (generated by
    // tools/gen_models.py) — the manifest avoids a 404 fetch per unmodeled item.
    const ITEM_ASSETS = new Set([
        'rune_scimitar', 'dragon_scimitar', 'dragon_dagger', 'venomous_fang',
        'ghrazi_rapier', 'abyssal_whip', 'corrupted_whip', 'armadyl_sword',
        'bandos_godsword', 'zamorak_godsword', 'saradomin_godsword',
        'armadyl_godsword', 'dragon_claws', 'granite_maul', 'elder_maul',
        'abyssal_bludgeon', 'zamorakian_hasta', 'scythe_of_vitur',
    ]);

    // dataURL for an item's icon, or null when the item has no model yet
    // (callers fall back to their text rendering).
    function itemIcon(itemId, size) {
        if (!ITEM_ASSETS.has(itemId)) return Promise.resolve(null);
        return renderIcon(`assets/items/${itemId}.vox`, size).catch(e => {
            console.warn('voxel: item icon failed', itemId, e);
            return null;
        });
    }

    // ── Battle scene ──────────────────────────────────────────────────────────
    // Three-quarter view: actors stand at world coordinates and are projected
    // through a per-battle camera that stays centered on the player and
    // rotates when the scene is dragged (tap = click-to-move / target). One
    // rAF loop per canvas; actors render to per-actor offscreen canvases
    // (tint/flash applied there) then blit onto the main canvas depth-sorted
    // with any scene props.

    // NPC ids with a model at assets/npcs/<id>.vox (generated per opponent
    // by tools/gen_models.py).
    const NPC_ASSETS = new Set([
        'goblin', 'swashbuckler', 'barbarian', 'desert_bandit', 'gladiator',
        'corsair', 'berserker', 'warlord', 'champion', 'rare_tourist', 'rare_gladiator',
    ]);

    // Single source of truth for scene geometry. Actors live at world
    // coordinates (x right, z toward the camera) on a round arena and are
    // projected through a fixed camera. worldH is the character's height in
    // world units (sets per-actor voxel size); facing is a world-space yaw.
    // The battle canvas renders at CSS resolution (BATTLE_PX = 1) with
    // integer voxel sizes and no image smoothing — sharp pixel art without
    // the blur of a stretched low-res buffer.
    const BATTLE_PX = 1;
    const POS_TILT = 0.7;      // camera pitch for world positions (steeper than
                               // the models' internal TILT so depth separates)
    const CAM_ANGLE0 = 0.10;   // initial camera yaw
    const CAM_DRAG = 0.010;    // camera yaw per dragged px
    const TAP_PX = 6;          // pointer travel below this = click, above = drag
    const ARENA_R = 5.2;       // arena circle radius, world units
    const WALK_R = 5;          // walkable tile radius (matches GameState.ArenaRadius)
    const FIELD_R = 12;        // grass extent of the field scene, world units
    const TILE_MS = 600;       // move-segment duration: one sim step per game tick
    const STRIDE = Math.PI;    // walk-phase radians per world unit (a step per tile)
    const CAM_FOV = 25;        // perspective divide (world units); larger = less distortion
    const ZOOM_MIN = 0.4, ZOOM_MAX = 2.5;
    const PITCH_MIN = 0.25, PITCH_MAX = 1.4;
    // Spawn tiles — must match GameState.StartDuel; live positions then come
    // from setBattlePositions as the sim moves the combatants.
    const LAYOUT = {
        player: { wx: 0.0, wz: 3.0,  facing: Math.PI, worldH: 2.8 },
        enemy:  { wx: 1.0, wz: -3.0, facing: 0,       worldH: 2.6 },
    };

    // Joint pivots / hand anchors / weapon grips, written by gen_models.py.
    let rigsPromise = null;
    function loadRigs() {
        rigsPromise ??= fetch('assets/rigs.json')
            .then(r => r.ok ? r.json() : null)
            .catch(() => null);
        return rigsPromise;
    }

    // px-per-world-unit and the screen y of the camera focus, fitted so the
    // arena (plus actor headroom) fills the canvas at any aspect.
    function camera(W, H, zoom = 1) {
        const px = Math.min(W / (ARENA_R * 2 + 0.6), H / (ARENA_R * 2 * POS_TILT + 7.5)) * zoom;
        return { px, cy: H * 0.55 };
    }
    // World → screen through the battle's live camera: translate to the
    // focus (follows the player), rotate by the drag yaw, project.
    // Perspective divide: ps = CAM_FOV / (CAM_FOV - rz). Near objects (rz > 0,
    // below on screen) appear larger; far objects (rz < 0, above) appear smaller.
    function proj(st, wx, wz, W, H) {
        const c = Math.cos(st.camYaw), sn = Math.sin(st.camYaw);
        const dx = wx - st.camFocus.wx, dz = wz - st.camFocus.wz;
        const rx = dx * c - dz * sn, rz = dx * sn + dz * c;
        const cm = camera(W, H, st.camZoom ?? 1);
        const ps = CAM_FOV / (CAM_FOV - rz);
        const pitch = st.camPitch ?? POS_TILT;
        return { x: W / 2 + rx * cm.px * ps, y: cm.cy + rz * cm.px * pitch * ps, rz, px: cm.px };
    }
    // Screen → world (ground plane): exact inverse of the perspective proj above.
    // Derived by solving: dy = rz * K / (CAM_FOV - rz), where K = px * pitch * CAM_FOV.
    // Rearranges to: rz = dy * CAM_FOV / (K + dy).
    function screenToWorld(st, sx, sy, W, H) {
        const cm = camera(W, H, st.camZoom ?? 1);
        const pitch = st.camPitch ?? POS_TILT;
        const dy = sy - cm.cy;
        const K = cm.px * pitch * CAM_FOV;
        const rz = Math.abs(K + dy) > 0.001 ? dy * CAM_FOV / (K + dy) : 0;
        const ps = CAM_FOV / (CAM_FOV - rz);
        const rx = (sx - W / 2) / (cm.px * ps);
        const c = Math.cos(st.camYaw), sn = Math.sin(st.camYaw);
        return { wx: st.camFocus.wx + rx * c + rz * sn,
                 wz: st.camFocus.wz - rx * sn + rz * c };
    }
    // Projected feet position of an actor (live position, not spawn).
    function anchor(actor, W, H) {
        return proj(actor.st, actor.pos.wx, actor.pos.wz, W, H);
    }

    // Attack-style accent colors (match .style-badge-* in terminal.css).
    const STYLE_COLORS = { melee: '#ff5555', ranged: '#7ddc7d', magic: '#6ec6ff' };

    // Per-weapon swing overrides (default comes from the weapon's AttackType:
    // stab/slash/crush) and each NPC's signature attack.
    const WEAPON_ANIMS = {
        abyssal_whip: 'lash', corrupted_whip: 'lash', dragon_claws: 'flurry',
        granite_maul: 'crush', elder_maul: 'crush', abyssal_bludgeon: 'crush',
    };
    const NPC_ANIMS = {
        goblin: 'crush', barbarian: 'crush', berserker: 'crush', warlord: 'crush',
        swashbuckler: 'slash', gladiator: 'slash', corsair: 'slash', champion: 'slash',
        rare_gladiator: 'slash', desert_bandit: 'slash', rare_tourist: 'stab',
    };

    const battles = new Map(); // canvasId → state

    // Actors own a copy of the voxel list ordered core-first, so HP-driven
    // erosion chips voxels off the outside while the silhouette survives.
    // view is what actually renders: the first visCount entries of ordered.
    function makeActor(model, base, tint, rig) {
        let cy = 0;
        for (const v of model.voxels) cy += v.y;
        cy /= model.voxels.length || 1;
        const ordered = model.voxels
            .map(v => ({ v, k: Math.hypot(v.x, (v.y - cy) * 0.7, v.z) + Math.random() * model.radius * 0.5 }))
            .sort((a, b) => a.k - b.k)
            .map(o => o.v);
        return {
            model, base, tint: tint ?? null, anims: [],
            bobPhase: Math.random() * 6.28, off: document.createElement('canvas'),
            ordered, visCount: ordered.length, lastRemoved: [],
            view: { ...model, voxels: ordered.slice(), scratch: new Array(ordered.length) },
            crumbled: false,
            rig: rig ?? null,               // rigs.json entry (legacy or v2)
            // v2 rigs stride so one stance half-cycle sweeps ±IK_STEP voxels
            // — the phase-exact condition for planted, skate-free feet.
            stride: rig?.parts
                ? Math.PI * model.height / (base.worldH * 2 * IK_STEP)
                : STRIDE,
            st: null,                       // back-ref to the battle (camera access)
            pos: { wx: base.wx, wz: base.wz },
            target: { wx: base.wx, wz: base.wz },
            seg: null,                      // live move segment (one per sim step)
            facing: base.facing,            // turns toward movement/opponent
            moving: false,
            walkPhase: 0,                   // gait phase, advances with distance
            weaponVox: null,                // merged held-weapon voxels (player)
            combined: null,                 // cached view+weapon render list
        };
    }

    // Part-pivot lookup for a rigged actor: parts 2..5 hinge at shoulders and
    // hips, the head at the neck; torso (0) never poses.
    function partPivots(rig) {
        const p = rig.pivots;
        return [null, p.neck, p.rShoulder, p.lShoulder, p.rHip, p.lHip];
    }

    // Erode or regrow an actor to `count` visible voxels. Voxels removed by an
    // erosion step are kept in lastRemoved so the hit event can turn exactly
    // those into debris.
    function setActorVisible(actor, count) {
        const N = actor.ordered.length;
        count = Math.max(8, Math.min(N, count | 0));
        if (count === actor.visCount) return;
        if (count < actor.visCount) actor.lastRemoved = actor.ordered.slice(count, actor.visCount);
        actor.visCount = count;
        actor.view.voxels = actor.ordered.slice(0, count);
        actor.view.scratch = new Array(count);
    }

    // Canvas position of a model-space voxel at the actor's base pose.
    function voxelCanvasPos(actor, v, W, H) {
        const p = anchor(actor, W, H);
        const S = actorScale(actor, W, H);
        const ang = actor.st.camYaw - actor.facing;
        const c = Math.cos(ang), sn = Math.sin(ang);
        const rx = v.x * c - v.z * sn, rz = v.x * sn + v.z * c;
        return { x: p.x + rx * S, y: p.y - v.y * S + rz * S * TILT, S };
    }

    function torso(actor, W, H) {
        const p = anchor(actor, W, H);
        const S = actorScale(actor, W, H);
        const ps = CAM_FOV / (CAM_FOV - p.rz);
        return { x: p.x, y: p.y - actor.model.height * S * ps * 0.55 };
    }

    // Voxel size for an actor: world height × camera scale, rounded to a whole
    // pixel so the offscreen stays sharp. Depth perspective is applied separately
    // at blit time (via ps = CAM_FOV / (CAM_FOV - rz)), so S never jumps
    // as actors move and the ~2× scale glitch during attacks is gone.
    function actorScale(actor, W, H) {
        const cm = camera(W, H, actor.st?.camZoom ?? 1);
        return Math.max(1, Math.round(cm.px * actor.base.worldH / actor.model.height));
    }

    // Motion amplitudes (lunges, knockback, debris velocity) scale with the
    // camera so the choreography looks the same at any canvas resolution.
    function motionScale(W, H) { return camera(W, H).px / 12; }

    // ── Pose curves ─────────────────────────────────────────────────────────
    // Per-weapon attack choreography over the 340ms 3-phase envelope
    // (0–0.4 anticipation, 0.4–0.55 strike, 0.55–1 recovery). Curves set the
    // weapon arm's pitch/yaw; the body lunge in animState stays but smaller.
    function lerp3(p, a, b, c) { // anticipation value a → strike b → settle c
        if (p < 0.4) return a * (p / 0.4);
        if (p < 0.55) return a + (b - a) * ((p - 0.4) / 0.15);
        const q = (p - 0.55) / 0.45;
        return b + (c - b) * q * (2 - q);
    }
    const ATTACK_POSES = {
        stab:   (p, t) => { t.pitch = lerp3(p, -0.55, 1.45, 0); t.dz = lerp3(p, -1.5, 3.5, 0); },
        slash:  (p, t) => { t.pitch = lerp3(p, 1.15, 1.25, 0); t.yaw = lerp3(p, -1.15, 1.2, 0); },
        lash:   (p, t) => { t.pitch = lerp3(p, 1.3, 1.35, 0); t.yaw = lerp3(p, -1.3, 1.6, 0); },
        crush:  (p, t) => { t.pitch = lerp3(p, 2.5, 0.75, 0); },
        flurry: (p, t) => {
            t.pitch = lerp3(p, 1.2, 1.3, 0);
            t.yaw = p < 0.75 ? Math.sin(p * 12.56) * 0.85 : Math.sin(9.42) * 0.85 * (1 - (p - 0.75) / 0.25);
        },
        bow:    (p, t) => { t.pitch = lerp3(p, 1.35, 0.9, 0); },
        cast:   (p, t) => { t.pitch = lerp3(p, 1.5, 1.1, 0); },
    };

    // Build the pose array for a rigged actor at scene time `now`.
    // Returns null when nothing poses (fast path in renderModel).
    function computePose(actor, now, windup) {
        if (!actor.rig) return null;
        if (actor.rig.parts) return computePoseV2(actor, now, windup);
        const pivots = partPivots(actor.rig);
        const mk = i => ({ pivot: pivots[i], pitch: 0, yaw: 0, dz: 0 });
        let pose = null;
        const ensure = i => {
            if (!pose) pose = [null, null, null, null, null, null];
            return pose[i] ??= mk(i);
        };

        const atk = actor.anims.find(a => a.type === 'attack');
        if (atk) {
            const p = (now - atk.t0) / atk.dur;
            if (p >= 0 && p <= 1) {
                (ATTACK_POSES[atk.kind] ?? ATTACK_POSES.slash)(p, ensure(P_RARM));
                if (atk.kind === 'bow') ensure(P_LARM).pitch = lerp3(p, 1.35, 1.35, 0);
                if (atk.kind === 'cast') ensure(P_LARM).pitch = lerp3(p, 0.9, 0.5, 0);
            }
        } else if (actor.moving) {
            // walk cycle driven by distance traveled (not time) so feet never
            // skate; drawActor grounds the stance foot with a matching body drop
            const s = Math.sin(actor.walkPhase) * 0.55;
            ensure(P_RLEG).pitch = s;   ensure(P_LLEG).pitch = -s;
            ensure(P_RARM).pitch = -s * 0.5; ensure(P_LARM).pitch = s * 0.5;
        } else if (windup) {
            // raise the weapon arm while the attack winds up
            ensure(P_RARM).pitch = 0.5 + Math.sin(now * 0.02) * 0.12;
        }
        return pose;
    }

    // ── v2 rig: hierarchical FK + analytic leg IK ─────────────────────────
    // The gait is phase-exact foot planting: walkPhase advances with ground
    // covered at actor.stride rad/wu, tuned so one stance half-cycle sweeps
    // the foot from +IK_STEP to −IK_STEP voxels — i.e. the planted foot
    // moves backward under the body at EXACTLY the body's speed, which is
    // the definition of a foot that does not skate. The swing leg arcs
    // forward with knee lift; the pelvis dips so knees stay bent; the foot
    // counter-rotates to stay flat through the whole stride.
    const IK_STEP = 8;         // stance half-sweep, voxels
    const IK_LIFT = 4;         // swing foot lift, voxels
    const IK_CROUCH = 1.4;     // moving pelvis drop base, voxels
    const IK_SWING_BOB = 1.2;  // pelvis bob amplitude (sine wave engine)
    const IK_HIP_SWAY = 0.15;  // hip yaw amplitude (radians)
    const IK_HIP_ROLL = 0.08;  // hip roll tilt (radians)
    const IK_TORSO_LEAN = 0.12; // torso forward lean on acceleration

    // 2-bone solve in the sagittal plane: hip at (0, hipY) reaching an ankle
    // at (tz forward, ty up). Returns forward-positive thigh/shin/foot
    // angles; renderModel pitch folds backward, so callers negate.
    function solveLeg(hipY, L1, L2, tz, ty) {
        const dy = hipY - ty;
        let d = Math.hypot(tz, dy);
        d = Math.min(L1 + L2 - 0.05, Math.max(Math.abs(L1 - L2) + 0.05, d));
        const a = Math.atan2(tz, dy);
        const cb = (L1 * L1 + d * d - L2 * L2) / (2 * L1 * d);
        const cg = (L1 * L1 + L2 * L2 - d * d) / (2 * L1 * L2);
        const thigh = a + Math.acos(Math.max(-1, Math.min(1, cb)));
        const shin = -(Math.PI - Math.acos(Math.max(-1, Math.min(1, cg))));
        return { thigh, shin, foot: -(thigh + shin) };
    }

    function computePoseV2(actor, now, windup) {
        const rig = actor.rig, parts = rig.parts;
        const T = new Array(parts.length).fill(null);
        const mk = i => ({ pivot: parts[i].pivot, pitch: 0, yaw: 0, dz: 0, dy: 0 });
        const ensure = i => T[i] ??= mk(i);

        // Gait blend eases limbs between authored idle and the moving gait
        // (~120ms) so starts and stops don't snap. dt from the scene clock,
        // so the blend freezes with hit-stop like everything else.
        const dt = Math.min(50, now - (actor._poseAt ?? now));
        actor._poseAt = now;
        actor.gaitBlend = Math.max(0, Math.min(1,
            (actor.gaitBlend ?? 0) + (actor.moving ? 1 : -1) * dt / 120));
        const g = actor.gaitBlend;
        const phase = ((actor.walkPhase % 6.2832) + 6.2832) % 6.2832;

        // Legs: IK gait while moving/blending, authored pose at rest.
        if (g > 0.001) {
            
            // 1. PELVIS ENGINE: Sine wave vertical motion (not cosine crouch)
            // Lowest at passing structure (phase 0, π) when feet spread wide
            // Highest at single-leg support (phase π/2, 3π/2)
            const passingStructurePhase = Math.abs(Math.sin(phase)); // 0 at passing, 1 at single support
            const pelvisY = -(IK_CROUCH + (1 - passingStructurePhase) * IK_SWING_BOB) * g;
            ensure(0).dy = pelvisY;
            
            // 2. HIP SWAYING & ROTATION: Counter-phase rotation + roll tilt
            // Yaw sways opposite to leg swing (left leg forward = right hip rotates forward)
            const hipYaw = Math.sin(phase) * IK_HIP_SWAY * g;
            ensure(0).yaw = hipYaw;
            
            // Hip roll: when foot leaves ground, that side's pelvis drops slightly
            // Phase crossover at π marks right foot takeoff
            const hipRoll = Math.sin(phase + Math.PI * 0.5) * IK_HIP_ROLL * g;
            ensure(0).dz = hipRoll;  // roll tilt around forward axis
            
            for (let li = 0; li < 2; li++) {
                const leg = rig.ik.legs[li];
                const hipPiv = parts[leg.hip].pivot, kneePiv = parts[leg.knee].pivot,
                      ankPiv = parts[leg.foot].pivot;
                const L1 = hipPiv[1] - kneePiv[1], L2 = kneePiv[1] - ankPiv[1];
                // this leg's phase: left leads by half a cycle
                const ph = li === 0 ? phase : (phase + Math.PI) % 6.2832;
                let relZ, lift = 0, droop = 0, hipYawLeg = 0;
                
                if (ph < Math.PI) {
                    // STANCE: Smooth backward sweep (not sharp linear)
                    // Use ease-out for natural weight transfer
                    const stance = ph / Math.PI;
                    const easeOut = 1 - (1 - stance) * (1 - stance);
                    relZ = IK_STEP * (1 - 2 * easeOut);
                } else {
                    // SWING: Parabolic arc (quick lift, glide, gentle landing)
                    const p = (ph - Math.PI) / Math.PI;
                    // Lift: sharp parabola upward then gentle ease down
                    lift = (4 * p * (1 - p)) * IK_LIFT;
                    // Forward motion: smooth ease-in-out along horizontal
                    const easeIO = p < 0.5 ? 2 * p * p : 1 - (-2 * p + 2) * (-2 * p + 2) / 2;
                    relZ = -IK_STEP + 2 * IK_STEP * easeIO;
                    // Subtle knee droop during swing for ground clearance
                    droop = Math.sin(p * Math.PI) * 0.3;
                    // Hip internal rotation during swing leg (adds realism)
                    hipYawLeg = (li === 1 ? -1 : 1) * Math.sin(p * Math.PI) * 0.1;
                }
                
                // solve pre-root-offset: ankle target rises by crouch so the
                // root drop lands the foot exactly on the ground
                const s = solveLeg(hipPiv[1], L1, L2, relZ * g,
                                   ankPiv[1] + lift * g - pelvisY);
                ensure(leg.hip).pitch = -s.thigh;
                ensure(leg.knee).pitch = -s.shin;
                ensure(leg.foot).pitch = -(s.foot + droop * g);
                
                // Hip internal rotation during swing for natural gait
                if (hipYawLeg !== 0) {
                    ensure(leg.hip).yaw = (ensure(leg.hip).yaw || 0) + hipYawLeg * g;
                }
            }
        }

        // Arms: attack/windup choreography wins; otherwise the run pump.
        const atk = actor.anims.find(a => a.type === 'attack');
        const RU = 2, LU = 3, RL = rig.handPart ?? 6, LL = 7;
        
        // 5. TORSO LAG & SECONDARY MOTION
        // Torso forward lean on acceleration (makes character feel responsive)
        if (g > 0.001 && actor.moving) {
           ensure(0).pitch = IK_TORSO_LEAN * g;  // lean forward slightly
        }
        
        // Impact jerks: when foot transitions from swing to stance (phase = π, 2π)
        // This simulates weight impact and removes floaty feeling
        const nextFootImpactL = (phase < Math.PI) ? false : (phase - Math.PI < 0.3); // right foot just landed
        const nextFootImpactR = (phase >= Math.PI) ? false : (phase < 0.3); // left foot just landed
        if ((nextFootImpactL || nextFootImpactR) && g > 0.001) {
           // Sharp downward impulse on pelvis and chest on landing
           const impactStrength = Math.max(0, 1 - (nextFootImpactL ? (phase - Math.PI) : phase) * 5);
           ensure(0).dy = (ensure(0).dy || 0) - impactStrength * 0.15 * g;
        }
        
        if (atk) {
            const p = (now - atk.t0) / atk.dur;
            if (p >= 0 && p <= 1) {
                (ATTACK_POSES[atk.kind] ?? ATTACK_POSES.slash)(p, ensure(RU));
                ensure(RL).pitch = T[RU].pitch * 0.35;   // elbow follow-through
                if (atk.kind === 'bow') ensure(LU).pitch = lerp3(p, 1.35, 1.35, 0);
                if (atk.kind === 'cast') ensure(LU).pitch = lerp3(p, 0.9, 0.5, 0);
            }
        } else if (g > 0.001) {
            const s = Math.sin(((actor.walkPhase % 6.2832) + 6.2832) % 6.2832) * 0.55 * g;
            ensure(RU).pitch = s;  ensure(LU).pitch = -s;
            ensure(RL).pitch = 0.5 * g; ensure(LL).pitch = 0.5 * g; // elbows pump bent
        } else if (windup) {
            ensure(RU).pitch = 0.5 + Math.sin(now * 0.02) * 0.12;
        }

        if (!T.some(t => t)) return null;
        // Link each part to its nearest posed ancestor so renderModel walks
        // the joint chain (foot → knee → hip → root).
        const pose = new Array(parts.length).fill(null);
        const resolve = i => {
            if (i === null || i === undefined) return null;
            if (pose[i] !== null) return pose[i];
            const up = resolve(parts[i].parent);
            if (T[i]) { T[i].up = up; return pose[i] = T[i]; }
            return pose[i] = up;
        };
        for (let i = 0; i < parts.length; i++) resolve(i);
        return pose;
    }

    // Render an actor to its offscreen canvas; returns {S, w, h, feetX, feetY}
    // where feet* locate the model's ground-center inside the offscreen.
    // Renders the eroded view (+ held weapon), posed.
    function renderActorOffscreen(actor, flashTint, W, H, angle, pose) {
        const m = actor.model;
        const S = actorScale(actor, W, H);
        // Swing padding: posed limbs (and the held weapon) can reach well
        // outside the static model bounds — overhead chops go highest.
        const reach = actor.rig ? (actor.weaponVox ? actor.weaponReach + 12 : 10) : 0;
        const w = Math.ceil((m.radius * 2 + 1 + 2 * reach) * S) + 2;
        const h = Math.ceil((m.height + 1 + m.radius * 2 * TILT + reach) * S) + 2;
        const off = actor.off;
        if (off.width !== w || off.height !== h) { off.width = w; off.height = h; }
        const ctx = off.getContext('2d');
        ctx.clearRect(0, 0, w, h);

        // Merge held-weapon voxels into the render list (rebuilt when erosion
        // or the weapon changes) so the painter's sort occludes correctly.
        let view = actor.view;
        if (actor.weaponVox) {
            if (!actor.combined || actor.combined.src !== actor.view.voxels || actor.combined.wsrc !== actor.weaponVox) {
                const voxels = actor.view.voxels.concat(actor.weaponVox);
                actor.combined = {
                    src: actor.view.voxels, wsrc: actor.weaponVox,
                    view: {
                        ...actor.view, voxels, scratch: new Array(voxels.length),
                        shadeTable: { ...actor.view.shadeTable, ...actor.weaponShade },
                    },
                };
            }
            view = actor.combined.view;
        }
        renderModel(ctx, view, angle ?? (actor.st.camYaw - actor.facing), S, w / 2, h - m.radius * TILT * S - S - 1, pose);
        const tint = flashTint ?? actor.tint;
        if (tint) {
            ctx.globalCompositeOperation = 'source-atop';
            ctx.fillStyle = tint;
            ctx.fillRect(0, 0, w, h);
            ctx.globalCompositeOperation = 'source-over';
        }
        return { S, w, h, feetX: w / 2, feetY: h - m.radius * TILT * S - 1 };
    }

    // Active animation offsets for an actor at time `now` (scene time).
    // Anims may carry a future t0 (projectile travel); they render nothing
    // until their time comes.
    function animState(actor, now, towardX, towardY, windup, ms) {
        const st = { dx: 0, dy: 0, flash: null, alpha: 1, scale: 1 };
        const len = Math.hypot(towardX, towardY) || 1;
        actor.anims = actor.anims.filter(a => now - a.t0 < a.dur);
        for (const a of actor.anims) {
            const p = Math.min(1, (now - a.t0) / a.dur);
            if (p < 0) continue;
            switch (a.type) {
                case 'attack': { // anticipation → strike → recovery, in place
                    let e;
                    if (p < 0.4) e = -(p / 0.4) * 0.6;                        // pull back
                    else if (p < 0.55) e = -0.6 + ((p - 0.4) / 0.15) * 1.6;   // snap forward
                    else { e = 1 - (p - 0.55) / 0.45; e *= e; }               // ease back
                    st.dx += (towardX / len) * 5 * ms * e;
                    st.dy += (towardY / len) * 5 * ms * e - Math.max(0, e) * 2 * ms;
                    break;
                }
                case 'hit': { // white → red flash + damage-scaled knockback
                    st.flash = p < 0.3 ? 'rgba(255,255,255,0.85)' : `rgba(224,32,16,${0.6 * (1 - p)})`;
                    const e = Math.sin(Math.PI * Math.min(1, p * 1.4));
                    const amp = (a.amp ?? 4) * ms;
                    st.dx -= (towardX / len) * amp * e;
                    st.dy -= (towardY / len) * amp * e;
                    break;
                }
                case 'dodge': { // sidestep, no flash (miss)
                    st.dx += Math.sin(Math.PI * p) * 8 * ms;
                    break;
                }
                case 'spawn': { // pop-in for endless wave swaps / duel resets
                    st.scale = Math.min(st.scale, 0.2 + 0.8 * p);
                    st.alpha = Math.min(st.alpha, p);
                    break;
                }
            }
        }
        // (No ambient hover-bob: feet stay planted; life comes from the
        // wobble yaw and the gait's body drop instead.)
        if (windup) { // lean back/up before the attack lands
            st.dx -= (towardX / len) * 2 * ms;
            st.dy -= (2 + Math.sin(now * 0.02) * 1.5) * ms;
            st.scale *= 1.04;
        }
        return st;
    }

    // Draws an actor. Crumbled actors are gone — their voxels are particles.
    function drawActor(ctx, W, H, actor, other, now, windup) {
        if (actor.crumbled) return null;
        const p = anchor(actor, W, H), po = anchor(other, W, H);
        const ax = p.x, ay = p.y;
        const a = animState(actor, now, po.x - p.x, po.y - p.y, windup, motionScale(W, H));
        const wobble = Math.sin(now * 0.0004 + actor.bobPhase) * 0.05; // ambient life
        const pose = computePose(actor, now, windup);
        const r = renderActorOffscreen(actor, a.flash, W, H, actor.st.camYaw - actor.facing + wobble, pose);

        // Gait grounding (legacy rigs only): with the legs split mid-stride
        // the hips sit lower — dropping the body by hip·(1−cos swing) plants
        // the stance foot instead of leaving both feet hovering. v2 rigs
        // ground their feet through the leg IK inside the pose itself.
        if (actor.moving && actor.rig && !actor.rig.parts) {
            const s = Math.sin(actor.walkPhase) * 0.55;
            a.dy += (1 - Math.cos(s)) * (actor.rig.pivots?.rHip?.[1] ?? 12) * r.S;
        }

        // Perspective scale at this actor's depth; psTot folds in the anim scale.
        const ps = CAM_FOV / (CAM_FOV - p.rz);
        const psTot = a.scale * ps;

        // Shadow on ground plane (player only — no distracting circle under every NPC).
        if (actor === actor.st.player) {
            ctx.fillStyle = `rgba(0,0,0,${0.30 * a.alpha})`;
            ctx.beginPath();
            ctx.ellipse(ax + a.dx * 0.4, ay,
                        actor.model.radius * r.S * ps * 0.9,
                        actor.model.radius * r.S * (actor.st?.camPitch ?? POS_TILT) * ps * 0.62, 0, 0, 6.2832);
            ctx.fill();
        }

        // Blit the offscreen: feetY inside the offscreen = h - radius*TILT*S - 1.
        // Place that pixel exactly at ay (ground), solving the "floating" offset.
        const bw = (r.w * psTot) | 0;
        const bh = (r.h * psTot) | 0;
        ctx.globalAlpha = a.alpha;
        ctx.drawImage(actor.off,
            (ax + a.dx - r.w / 2 * psTot) | 0,
            (ay + a.dy - (r.h - actor.model.radius * r.S * TILT - 1) * psTot) | 0,
            bw, bh);
        ctx.globalAlpha = 1;
        return a;
    }

    // Attach a weapon model to an actor's hand: weapon voxels are translated
    // grip→hand, tagged as the weapon arm, and given remapped color indices so
    // they can carry their own shade table into the merged render list. The
    // painter's sort then occludes weapon vs body correctly, and the whole
    // thing follows the rArm pose (swings, walk counter-swing, wind-up).
    function attachWeapon(actor, model, grip) {
        if (!model) {
            actor.weaponVox = null; actor.weaponShade = null;
            actor.weaponReach = 0; actor.combined = null;
            return;
        }
        const hand = actor.rig?.hand ?? [actor.model.radius * 0.6, actor.model.height * 0.4, 0];
        const g = grip ?? [0, 2, 0];
        const shade = {};
        for (const k of Object.keys(model.shadeTable)) shade[1000 + (+k)] = model.shadeTable[k];
        let reach = 0;
        const handPart = actor.rig?.handPart ?? P_RARM; // v2: forearm chain
        actor.weaponVox = model.voxels.map(v => {
            const y = v.y - g[1] + hand[1];
            if (y - hand[1] > reach) reach = y - hand[1];
            return {
                x: v.x - g[0] + hand[0], y, z: v.z - g[2] + hand[2],
                ci: 1000 + v.ci, part: handPart,
            };
        });
        actor.weaponShade = shade;
        actor.weaponReach = Math.ceil(reach);
        actor.combined = null;
    }

    // Debris burst at (a subset of) the given voxels' positions.
    function spawnDebris(st, actor, other, count, t0, sourceVoxels) {
        const W = st.canvas.width, H = st.canvas.height;
        const src = (sourceVoxels && sourceVoxels.length)
            ? sourceVoxels
            : actor.ordered.slice(Math.max(0, actor.visCount - 30), actor.visCount);
        if (!src.length) return;
        const pa = anchor(actor, W, H), po = anchor(other, W, H);
        const ms = motionScale(W, H);
        const dirX = Math.sign(pa.x - po.x) || 1; // away from attacker
        const floor = pa.y + 2;
        for (let i = 0; i < count && st.particles.length < 150; i++) {
            const v = src[(Math.random() * src.length) | 0];
            const p = voxelCanvasPos(actor, v, W, H);
            st.particles.push({
                x: p.x, y: p.y,
                vx: (dirX * (0.4 + Math.random() * 1.4) + (Math.random() - 0.5) * 0.8) * ms,
                vy: (-1.2 - Math.random() * 1.6) * ms,
                size: Math.max(1, p.S - (Math.random() < 0.5 ? 1 : 0)),
                color: (actor.model.shadeTable[v.ci] ?? ['#888', '#888', '#888', '#888'])[3],
                t0, life: 700 + Math.random() * 500, floor,
            });
        }
    }

    // Death: the whole remaining model (held weapon included) bursts into
    // physical voxel particles that scatter, bounce, and fade.
    function crumbleActor(st, actor, other) {
        const W = st.canvas.width, H = st.canvas.height;
        const shade = actor.combined?.view.shadeTable ?? actor.model.shadeTable;
        const vs = actor.combined?.view.voxels ?? actor.view.voxels;
        const step = vs.length > 400 ? 2 : 1;
        const pa = anchor(actor, W, H), po = anchor(other, W, H);
        const ms = motionScale(W, H);
        const dirX = Math.sign(pa.x - po.x) || 1;
        const cx = pa.x;
        const t0 = st.time;
        for (let i = 0; i < vs.length; i += step) {
            const v = vs[i];
            const p = voxelCanvasPos(actor, v, W, H);
            st.particles.push({
                x: p.x, y: p.y,
                vx: dirX * Math.random() * 1.0 * ms + (p.x - cx) * 0.03,
                vy: (-0.4 - Math.random() * 2.2) * ms,
                size: p.S,
                color: (shade[v.ci] ?? ['#888', '#888', '#888', '#888'])[3],
                t0, life: 800 + Math.random() * 900,
                floor: pa.y + 2 + Math.random() * 3,
            });
        }
        actor.crumbled = true;
        actor.anims = [];
    }

    function drawTelegraphGlow(ctx, W, H, actor, now) {
        const p = anchor(actor, W, H);
        const S = actorScale(actor, W, H);
        const ps = CAM_FOV / (CAM_FOV - p.rz);
        const cx = p.x;
        const cy = p.y - actor.model.height * S * ps * 0.45;
        const rad = actor.model.height * S * ps * 0.85;
        const pulse = 0.22 + 0.14 * Math.sin(now * 0.006);
        const g = ctx.createRadialGradient(cx, cy, rad * 0.15, cx, cy, rad);
        g.addColorStop(0, `rgba(204,68,255,${pulse})`);
        g.addColorStop(1, 'rgba(204,68,255,0)');
        ctx.fillStyle = g;
        ctx.fillRect(cx - rad, cy - rad, rad * 2, rad * 2);
    }

    // ── Ground scenes ─────────────────────────────────────────────────────────
    // Drawn every frame (the camera rotates and follows the player, so the
    // ground can't be pre-rendered). 'arena': the round checkered duel ring.
    // 'field': open grass with prop set-dressing (test fights).

    function tileQuad(st, ctx, tx, tz, W, H) {
        const p0 = proj(st, tx, tz, W, H), p1 = proj(st, tx + 1, tz, W, H),
              p2 = proj(st, tx + 1, tz + 1, W, H), p3 = proj(st, tx, tz + 1, W, H);
        ctx.beginPath();
        ctx.moveTo(p0.x, p0.y); ctx.lineTo(p1.x, p1.y);
        ctx.lineTo(p2.x, p2.y); ctx.lineTo(p3.x, p3.y);
        ctx.closePath(); ctx.fill();
    }

    function drawArenaScene(st, ctx, W, H) {
        const ring = new Path2D();
        for (let i = 0; i <= 64; i++) {
            const a = i / 64 * Math.PI * 2;
            const p = proj(st, Math.cos(a) * ARENA_R, Math.sin(a) * ARENA_R, W, H);
            if (i === 0) ring.moveTo(p.x, p.y); else ring.lineTo(p.x, p.y);
        }
        ring.closePath();

        // checker tiles clipped to the ring so the arena edge is clean
        ctx.save();
        ctx.clip(ring);
        const R = Math.ceil(ARENA_R);
        for (let tx = -R - 1; tx <= R; tx++) {
            for (let tz = -R - 1; tz <= R; tz++) {
                ctx.fillStyle = ((tx + tz) & 1) ? '#2b2331' : '#241d29';
                tileQuad(st, ctx, tx, tz, W, H);
            }
        }
        ctx.restore();
        ctx.strokeStyle = '#4a3a55';
        ctx.lineWidth = 1.5;
        ctx.stroke(ring);
    }

    // Deterministic per-tile grass shade (cached) — mostly quiet greens with
    // the odd dirt patch so the field doesn't read as a flat fill.
    function grassColor(st, tx, tz) {
        const key = tx * 4096 + tz;
        let c = st.tileColors.get(key);
        if (!c) {
            let h = (tx * 374761393 + tz * 668265263) | 0;
            h = ((h ^ (h >> 13)) * 1274126177) | 0;
            const v = ((h >>> 16) & 255) / 255;
            c = v > 0.94 ? '#3d3423' : v > 0.62 ? '#243d21' : v > 0.30 ? '#1f351e' : '#28421f';
            st.tileColors.set(key, c);
        }
        return c;
    }

    function drawFieldScene(st, ctx, W, H) {
        const m = camera(W, H).px * 1.5; // cull margin
        for (let tx = -FIELD_R; tx < FIELD_R; tx++) {
            for (let tz = -FIELD_R; tz < FIELD_R; tz++) {
                const p = proj(st, tx + 0.5, tz + 0.5, W, H);
                if (p.x < -m || p.x > W + m || p.y < -m || p.y > H + m) continue;
                ctx.fillStyle = grassColor(st, tx, tz);
                tileQuad(st, ctx, tx, tz, W, H);
            }
        }
    }

    function drawScene(st, ctx, W, H) {
        const g = ctx.createLinearGradient(0, 0, 0, H);
        if (st.scene === 'field') {
            g.addColorStop(0, '#0a120c');
            g.addColorStop(0.5, '#0e1810');
            g.addColorStop(1, '#0c140d');
        } else {
            g.addColorStop(0, '#0b0b12');
            g.addColorStop(0.45, '#12101a');
            g.addColorStop(1, '#191420');
        }
        ctx.fillStyle = g;
        ctx.fillRect(0, 0, W, H);
        if (st.scene === 'field') drawFieldScene(st, ctx, W, H);
        else drawArenaScene(st, ctx, W, H);
    }

    // Field set-dressing, placed outside the walkable radius. Loaded lazily
    // into st.props; drawn depth-sorted with the actors.
    const FIELD_PROPS = [
        // trees stay ≥ 8.5 wu out so their canopies never occlude a fight
        // at the walkable edge (WALK_R = 5)
        { id: 'tree', wx: -9.0, wz: -4.5, worldH: 5.4 },
        { id: 'tree', wx: 8.5,  wz: -7.5, worldH: 4.6 },
        { id: 'tree', wx: 9.2,  wz: 5.5,  worldH: 5.8 },
        { id: 'tree', wx: -8.5, wz: 8.0,  worldH: 5.0 },
        { id: 'rock', wx: -6.6, wz: 1.5,  worldH: 1.4 },
        { id: 'rock', wx: 3.5,  wz: -7.4, worldH: 1.1 },
        { id: 'bush', wx: 6.6,  wz: -1.8, worldH: 1.1 },
        { id: 'bush', wx: -3.0, wz: -7.1, worldH: 0.9 },
        { id: 'bush', wx: 1.5,  wz: 7.4,  worldH: 1.0 },
    ];

    function drawProp(st, ctx, pr, W, H) {
        const p = proj(st, pr.wx, pr.wz, W, H);
        const ps = CAM_FOV / (CAM_FOV - p.rz);
        const S = Math.max(1, Math.round(p.px * pr.worldH * ps / pr.model.height));
        ctx.fillStyle = 'rgba(0,0,0,0.25)';
        ctx.beginPath();
        ctx.ellipse(p.x, p.y, pr.model.radius * S * 0.9,
            pr.model.radius * S * (st.camPitch ?? POS_TILT) * 0.6, 0, 0, 6.2832);
        ctx.fill();
        renderModel(ctx, pr.model, st.camYaw, S, p.x, p.y);
    }

    // Pulsing tile outline where the last ground click landed (walk order).
    function drawMoveMarker(st, ctx, W, H, now) {
        if (!st.moveMarker) return;
        const age = now - st.moveMarker.t0;
        if (age > 900) { st.moveMarker = null; return; }
        const { wx, wz } = st.moveMarker;
        const p0 = proj(st, wx - 0.5, wz - 0.5, W, H), p1 = proj(st, wx + 0.5, wz - 0.5, W, H),
              p2 = proj(st, wx + 0.5, wz + 0.5, W, H), p3 = proj(st, wx - 0.5, wz + 0.5, W, H);
        ctx.save();
        ctx.globalAlpha = 1 - age / 900;
        ctx.strokeStyle = '#ffd166';
        ctx.lineWidth = 1.5;
        ctx.beginPath();
        ctx.moveTo(p0.x, p0.y); ctx.lineTo(p1.x, p1.y);
        ctx.lineTo(p2.x, p2.y); ctx.lineTo(p3.x, p3.y);
        ctx.closePath(); ctx.stroke();
        ctx.restore();
    }

    // Pulsing starburst above the enemy while their attack winds up; color
    // encodes the incoming style so prayer switches can be timed off it.
    function drawWindupGlint(ctx, W, H, actor, now, color) {
        const p = anchor(actor, W, H);
        const S = actorScale(actor, W, H);
        const ps = CAM_FOV / (CAM_FOV - p.rz);
        const x = p.x;
        const y = p.y - actor.model.height * S * ps - S * ps * 3;
        const pulse = 0.5 + 0.5 * Math.sin(now * 0.02);
        const r = actor.model.height * S * ps * 0.22 * (0.7 + 0.5 * pulse);
        ctx.save();
        ctx.globalAlpha = 0.5 + 0.5 * pulse;
        ctx.strokeStyle = color;
        ctx.lineWidth = Math.max(1.5, S * ps * 0.7);
        for (let i = 0; i < 4; i++) {
            const ang = i * Math.PI / 4 + now * 0.003;
            ctx.beginPath();
            ctx.moveTo(x - Math.cos(ang) * r, y - Math.sin(ang) * r);
            ctx.lineTo(x + Math.cos(ang) * r, y + Math.sin(ang) * r);
            ctx.stroke();
        }
        ctx.restore();
    }

    // Impact slash over the defender: sweeping arcs + radial sparks, fading out.
    function drawSlash(ctx, x, y, r, p, color) {
        ctx.save();
        ctx.globalAlpha = 1 - p;
        ctx.strokeStyle = color;
        ctx.lineWidth = Math.max(2, r * 0.06);
        const sweep = p * 1.4;
        for (let i = 0; i < 3; i++) {
            ctx.beginPath();
            ctx.arc(x, y, r * (0.45 + i * 0.25), -2.2 + sweep, -0.9 + sweep);
            ctx.stroke();
        }
        ctx.lineWidth = Math.max(1, r * 0.03);
        for (let i = 0; i < 5; i++) {
            const ang = i * 1.2566 + 0.6;
            const r0 = r * (0.25 + 0.55 * p), r1 = r * (0.5 + 0.8 * p);
            ctx.beginPath();
            ctx.moveTo(x + Math.cos(ang) * r0, y + Math.sin(ang) * r0);
            ctx.lineTo(x + Math.cos(ang) * r1, y + Math.sin(ang) * r1);
            ctx.stroke();
        }
        ctx.restore();
    }

    function npcModelUrl(enemyId) {
        return NPC_ASSETS.has(enemyId) ? `assets/npcs/${enemyId}.vox` : 'assets/player.vox';
    }

    // Unmodeled enemies reuse the player model with a permanent red wash so a
    // fight never looks like a mirror match.
    function npcFallbackTint(enemyId) {
        return NPC_ASSETS.has(enemyId) ? null : 'rgba(224,48,16,0.28)';
    }

    async function initBattle(canvasId, opts) {
        destroyBattle(canvasId);

        const [playerModel, rigs] = await Promise.all([
            loadModel(opts.playerUrl).catch(e => {
                console.warn('voxel: battle player model failed', e);
                return null;
            }),
            loadRigs(),
        ]);
        const enemyModel = await loadModel(npcModelUrl(opts.enemyId)).catch(() => null)
            ?? await loadModel('assets/player.vox').catch(e => {
                console.warn('voxel: battle enemy model failed', e);
                return null;
            });
        if (!playerModel || !enemyModel) return;

        const canvas = document.getElementById(canvasId);
        if (!canvas || battles.has(canvasId)) return; // unmounted or re-init raced ahead

        const rigOf = id => rigs?.characters?.[id] ?? rigs?.characters?.player ?? null;
        const st = {
            canvas,
            ctx: canvas.getContext('2d'),
            rigs,
            player: makeActor(playerModel, LAYOUT.player, null, rigs?.characters?.player),
            enemy: makeActor(enemyModel, LAYOUT.enemy, npcFallbackTint(opts.enemyId), rigOf(opts.enemyId)),
            rigOf,
            enemyId: opts.enemyId,
            enemySwapToken: 0,
            weaponToken: 0,
            weaponId: null,
            flags: { telegraph: false, windup: null },
            lastWindupStyle: null,
            targetPulse: -1e9,    // click-to-target chevron
            scene: opts.scene === 'field' ? 'field' : 'arena',
            dotnet: opts.dotnetRef ?? null,   // Blazor callbacks (clicks)
            camYaw: CAM_ANGLE0,               // drag-to-rotate camera yaw
            camZoom: 1.0,                     // scroll/pinch zoom (ZOOM_MIN–ZOOM_MAX)
            camPitch: POS_TILT,               // vertical tilt (PITCH_MIN–PITCH_MAX)
            camFocus: { wx: LAYOUT.player.wx, wz: LAYOUT.player.wz },
            tileColors: new Map(),
            props: [],            // { model, wx, wz, worldH } (field scene)
            moveMarker: null,     // last ground-click tile pulse
            drag: null,           // active pointer gesture
            effects: [],
            particles: [],
            projectiles: [],
            // Scene time: freezes during hit-stop, crawls during slow-mo.
            time: 0,
            lastReal: performance.now(),
            freezeUntil: 0,       // real-time ms
            slowUntil: 0,         // real-time ms
            pendingFreezes: [],   // { at: sceneTime, dur: realMs }
            cam: null,            // { amt, x, y, t0, dur } punch-zoom
            shake: null,          // { mag, t0, dur }
            delayEnemyVis: 0,     // projectile travel offsets, consumed by the
            delayPlayerVis: 0,    // matching hit event
            raf: 0,
            ro: null,
        };
        st.player.st = st;
        st.enemy.st = st;

        // Field props load in the background and pop in as they arrive.
        if (st.scene === 'field') {
            for (const spec of FIELD_PROPS) {
                loadModel(`assets/props/${spec.id}.vox`).then(model => {
                    if (battles.get(canvasId) === st) st.props.push({ ...spec, model });
                }).catch(() => { /* prop missing: field stays grass-only */ });
            }
        }

        // Logical resolution follows the CSS box (÷BATTLE_PX). The ground is
        // redrawn every frame (rotating camera), so resize only sizes the canvas.
        const fit = () => {
            const w = Math.max(60, Math.round(canvas.clientWidth / BATTLE_PX));
            const h = Math.max(60, Math.round(canvas.clientHeight / BATTLE_PX));
            if (canvas.width !== w) canvas.width = w;
            if (canvas.height !== h) canvas.height = h;
        };
        fit();
        st.ro = new ResizeObserver(fit);
        st.ro.observe(canvas);

        // Hitsplat zones + overhead prayer icons follow the actors' projected
        // positions (throttled — they move at walk speed, not frame speed).
        const tracked = [ // element id, actor key (survives enemy swaps), height frac, x offset
            [opts.zonePlayerId, 'player', 0.85, 0],
            [opts.zoneNpcId, 'enemy', 0.85, 0],
            ['overhead-player', 'player', 1.02, -0.06],
            ['overhead-npc', 'enemy', 1.02, 0.10],
        ];
        st.trackAnchors = (W, H) => {
            for (const [id, key, hFrac, xOff] of tracked) {
                const el = document.getElementById(id);
                if (!el) continue;
                const actor = st[key];
                const p = anchor(actor, W, H);
                const ps = CAM_FOV / (CAM_FOV - p.rz);
                const top = p.y - actor.model.height * actorScale(actor, W, H) * ps * hFrac;
                el.style.left = ((p.x / W + xOff) * 100) + '%';
                el.style.top = (Math.max(0, top) / H * 100) + '%';
            }
        };

        // Pointer gestures:
        //   1 finger horizontal drag → orbit (yaw)
        //   2 fingers pinch          → zoom
        //   2 fingers vertical shift → pitch (tilt up/down)
        //   tap (< TAP_PX travel)    → click (enemy re-engages, ground = walk)
        //   mouse wheel              → zoom
        st.pointers = new Map(); // pointerId → { x, y }
        st.pinch = null;         // { dist0, zoom0, midY0, pitch0 }

        st.onDown = ev => {
            canvas.setPointerCapture(ev.pointerId);
            st.pointers.set(ev.pointerId, { x: ev.clientX, y: ev.clientY });
            if (st.pointers.size === 1) {
                st.drag = { x: ev.clientX, y: ev.clientY, yaw0: st.camYaw, moved: 0 };
            } else if (st.pointers.size === 2) {
                const pts = [...st.pointers.values()];
                st.pinch = {
                    dist0: Math.hypot(pts[0].x - pts[1].x, pts[0].y - pts[1].y),
                    zoom0: st.camZoom,
                    midY0: (pts[0].y + pts[1].y) / 2,
                    pitch0: st.camPitch,
                };
                st.drag = null; // 2-finger gesture supersedes single-drag
            }
        };
        st.onMove = ev => {
            st.pointers.set(ev.pointerId, { x: ev.clientX, y: ev.clientY });
            if (st.pointers.size >= 2 && st.pinch) {
                const pts = [...st.pointers.values()];
                const dist = Math.hypot(pts[0].x - pts[1].x, pts[0].y - pts[1].y);
                const midY = (pts[0].y + pts[1].y) / 2;
                st.camZoom = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX,
                    st.pinch.zoom0 * dist / st.pinch.dist0));
                // upward drag (negative delta) = look more from above → higher pitch
                const pitchDelta = (st.pinch.midY0 - midY) * 0.004;
                st.camPitch = Math.max(PITCH_MIN, Math.min(PITCH_MAX,
                    st.pinch.pitch0 + pitchDelta));
            } else if (st.drag && st.pointers.size === 1) {
                st.drag.moved = Math.max(st.drag.moved,
                    Math.hypot(ev.clientX - st.drag.x, ev.clientY - st.drag.y));
                if (st.drag.moved > TAP_PX)
                    st.camYaw = st.drag.yaw0 + (ev.clientX - st.drag.x) * CAM_DRAG;
            }
        };
        st.onUp = ev => {
            const wasSingle = st.pointers.size === 1;
            const d = st.drag;
            st.pointers.delete(ev.pointerId);
            if (st.pointers.size < 2) st.pinch = null;

            // Tap: only when a single pointer lifted with < TAP_PX travel.
            if (wasSingle && d && d.moved <= TAP_PX) {
                const rect = canvas.getBoundingClientRect();
                const x = (ev.clientX - rect.left) / rect.width * canvas.width;
                const y = (ev.clientY - rect.top) / rect.height * canvas.height;
                const W = canvas.width, H = canvas.height;

                // Enemy first: generous screen-rect hit-test.
                const e = st.enemy;
                if (!e.crumbled) {
                    const p = anchor(e, W, H);
                    const S = actorScale(e, W, H);
                    const ePs = CAM_FOV / (CAM_FOV - p.rz);
                    if (Math.abs(x - p.x) < e.model.radius * S * ePs * 1.5 &&
                        y > p.y - e.model.height * S * ePs - 8 && y < p.y + 6) {
                        st.targetPulse = st.time;
                        st.dotnet?.invokeMethodAsync('OnEnemyClick');
                        st.drag = null;
                        return;
                    }
                }

                // Ground: unproject to a tile, clamp to the walkable circle.
                const w = screenToWorld(st, x, y, W, H);
                let tx = Math.round(w.wx), tz = Math.round(w.wz);
                let guard = 40;
                while (tx * tx + tz * tz > WALK_R * WALK_R && guard-- > 0) {
                    if (Math.abs(tx) >= Math.abs(tz)) tx -= Math.sign(tx);
                    else tz -= Math.sign(tz);
                }
                st.moveMarker = { wx: tx, wz: tz, t0: st.time };
                st.dotnet?.invokeMethodAsync('OnGroundClick', tx, tz);
            }

            // If one finger remains after lifting, re-anchor single-drag.
            if (st.pointers.size === 1) {
                const [pt] = st.pointers.values();
                st.drag = { x: pt.x, y: pt.y, yaw0: st.camYaw, moved: 0 };
            } else if (st.pointers.size === 0) {
                st.drag = null;
            }
        };
        st.onCancel = ev => {
            st.pointers.delete(ev.pointerId);
            if (st.pointers.size < 2) st.pinch = null;
            if (st.pointers.size === 0) st.drag = null;
        };
        // Scroll wheel: zoom in/out.
        st.onWheel = ev => {
            ev.preventDefault();
            const factor = ev.deltaY > 0 ? 0.92 : 1 / 0.92;
            st.camZoom = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, st.camZoom * factor));
        };
        canvas.style.touchAction = 'none';       // let pointermove drags rotate on touch
        canvas.addEventListener('pointerdown', st.onDown);
        canvas.addEventListener('pointermove', st.onMove);
        canvas.addEventListener('pointerup', st.onUp);
        canvas.addEventListener('pointercancel', st.onCancel);
        canvas.addEventListener('wheel', st.onWheel, { passive: false });

        const loop = () => {
            // Scene clock: dt freezes for hit-stop, crawls for killing-blow
            // slow-mo; everything below runs on st.time, so all motion —
            // anims, bob, debris, projectiles — obeys the same clock.
            const real = performance.now();
            let dt = Math.min(50, real - st.lastReal);
            st.lastReal = real;
            if (real < st.freezeUntil) dt = 0;
            else if (real < st.slowUntil) dt *= 0.3;
            st.time += dt;
            const now = st.time;
            for (let i = st.pendingFreezes.length - 1; i >= 0; i--) {
                if (st.pendingFreezes[i].at <= now) {
                    st.freezeUntil = real + st.pendingFreezes[i].dur;
                    st.pendingFreezes.splice(i, 1);
                }
            }

            const W = canvas.width, H = canvas.height;
            const ctx = st.ctx;
            const ms = motionScale(W, H);
            ctx.clearRect(0, 0, W, H);
            ctx.save();
            ctx.imageSmoothingEnabled = false; // nearest-neighbor blits stay crisp

            // Camera: punch-zoom anchored on the victim, integer-snapped shake.
            // (No ambient zoom — continuous rescaling blurs the pixel art.)
            if (st.cam) {
                const p = (now - st.cam.t0) / st.cam.dur;
                if (p >= 1) st.cam = null;
                else if (p >= 0) {
                    const z = 1 + st.cam.amt * (1 - p) * (1 - p);
                    ctx.translate(st.cam.x, st.cam.y); ctx.scale(z, z); ctx.translate(-st.cam.x, -st.cam.y);
                }
            }
            if (st.shake) {
                const p = (now - st.shake.t0) / st.shake.dur;
                if (p >= 1) st.shake = null;
                else if (p >= 0)
                    ctx.translate(((Math.random() * 2 - 1) * st.shake.mag * ms) | 0,
                                  ((Math.random() * 2 - 1) * st.shake.mag * ms) | 0);
            }

            // Movement: play each actor's segment at constant velocity, timed
            // to land exactly when the next sim step is due (TILE_MS) — no
            // per-tile stall, and longer (running) segments just move faster.
            // Face travel direction while moving, else the opponent.
            for (const key of ['player', 'enemy']) {
                const actor = st[key];
                const other = key === 'player' ? st.enemy : st.player;
                if (actor.crumbled) { actor.moving = false; continue; }
                let destFacing;
                if (actor.seg) {
                    const s = actor.seg;
                    const p = Math.min(1, (st.time - s.t0) / TILE_MS);
                    const nx = s.x0 + (s.x1 - s.x0) * p, nz = s.z0 + (s.z1 - s.z0) * p;
                    actor.walkPhase += Math.hypot(nx - actor.pos.wx, nz - actor.pos.wz) * actor.stride;
                    actor.pos.wx = nx; actor.pos.wz = nz;
                    actor.moving = p < 1;
                    destFacing = Math.atan2(s.x1 - s.x0, s.z1 - s.z0);
                    if (p >= 1) {
                        actor.seg = null;
                        destFacing = Math.atan2(other.pos.wx - actor.pos.wx, other.pos.wz - actor.pos.wz);
                    }
                } else {
                    actor.moving = false;
                    destFacing = Math.atan2(other.pos.wx - actor.pos.wx, other.pos.wz - actor.pos.wz);
                }
                let da = destFacing - actor.facing;
                while (da > Math.PI) da -= 6.2832;
                while (da < -Math.PI) da += 6.2832;
                actor.facing += da * Math.min(1, dt * 0.03);
            }

            // Camera: rigid lock on the player (OSRS-style). The actor's own
            // glide is already smooth, so no follow-lag is needed — lag here
            // just reads as the world swimming.
            st.camFocus.wx = st.player.pos.wx;
            st.camFocus.wz = st.player.pos.wz;
            st.trackAnchors(W, H);

            drawScene(st, ctx, W, H);
            drawMoveMarker(st, ctx, W, H, now);
            if (st.flags.telegraph) drawTelegraphGlow(ctx, W, H, st.enemy, now);
            // Painter's order: props and actors sorted far → near (the camera
            // rotates, so either combatant can be the near one).
            const order = [];
            for (const pr of st.props)
                order.push({ rz: proj(st, pr.wx, pr.wz, W, H).rz,
                             draw: () => drawProp(st, ctx, pr, W, H) });
            order.push({ rz: anchor(st.enemy, W, H).rz,
                         draw: () => drawActor(ctx, W, H, st.enemy, st.player, now, st.flags.windup) });
            order.push({ rz: anchor(st.player, W, H).rz,
                         draw: () => drawActor(ctx, W, H, st.player, st.enemy, now, null) });
            order.sort((a, b) => a.rz - b.rz);
            for (const o of order) o.draw();
            if (st.flags.windup && !st.enemy.crumbled)
                drawWindupGlint(ctx, W, H, st.enemy, now, STYLE_COLORS[st.flags.windup] ?? '#ffffff');

            // Target chevron pulse (click-to-target scaffold)
            if (now - st.targetPulse < 900 && !st.enemy.crumbled) {
                const tp = anchor(st.enemy, W, H);
                const tS = actorScale(st.enemy, W, H);
                const tPs = CAM_FOV / (CAM_FOV - tp.rz);
                const ty = tp.y - st.enemy.model.height * tS * tPs - 10 * ms - Math.sin((now - st.targetPulse) * 0.02) * 3 * ms;
                ctx.globalAlpha = 1 - (now - st.targetPulse) / 900;
                ctx.fillStyle = '#ffd166';
                ctx.beginPath();
                ctx.moveTo(tp.x, ty);
                ctx.lineTo(tp.x - 5 * ms, ty - 7 * ms);
                ctx.lineTo(tp.x + 5 * ms, ty - 7 * ms);
                ctx.closePath(); ctx.fill();
                ctx.globalAlpha = 1;
            }

            // Impact slashes (style-color cue; debris carries the weight now)
            st.effects = st.effects.filter(e => now - e.t0 < e.dur);
            for (const e of st.effects) {
                if (now < e.t0) continue;
                const on = e.on === 'player' ? st.player : st.enemy;
                const t = torso(on, W, H);
                const onP = anchor(on, W, H);
                const onPs = CAM_FOV / (CAM_FOV - onP.rz);
                drawSlash(ctx, t.x, t.y, on.model.height * actorScale(on, W, H) * onPs * 0.5,
                    (now - e.t0) / e.dur, e.color);
            }

            // Projectiles (arrow line / swirling motes)
            st.projectiles = st.projectiles.filter(pr => now - pr.t0 < pr.dur);
            const pxl = Math.max(2, Math.round(2 * ms)); // projectile pixel size
            for (const pr of st.projectiles) {
                const p = (now - pr.t0) / pr.dur;
                if (p < 0) continue;
                const x = pr.x0 + (pr.x1 - pr.x0) * p;
                const y = pr.y0 + (pr.y1 - pr.y0) * p - Math.sin(Math.PI * p) * (pr.style === 'ranged' ? 7 : 3) * ms;
                ctx.fillStyle = STYLE_COLORS[pr.style] ?? '#fff';
                if (pr.style === 'magic') {
                    for (let i = 0; i < 4; i++) {
                        const a = now * 0.02 + i * 1.57;
                        ctx.fillRect((x + Math.cos(a) * 3 * ms) | 0, (y + Math.sin(a) * 2 * ms) | 0, pxl, pxl);
                    }
                } else {
                    const dx = pr.x1 - pr.x0, dy = pr.y1 - pr.y0, L = Math.hypot(dx, dy) || 1;
                    for (let i = 0; i < 3; i++)
                        ctx.fillRect((x - dx / L * i * pxl) | 0, (y - dy / L * i * pxl) | 0, pxl, pxl);
                }
            }

            // Debris: gravity, floor bounce, fade over the last 30% of life
            st.particles = st.particles.filter(pt => now - pt.t0 < pt.life);
            for (const pt of st.particles) {
                if (now < pt.t0) continue;
                const k = dt / 16.7;
                pt.vy += 0.28 * ms * k;
                pt.x += pt.vx * k;
                pt.y += pt.vy * k;
                if (pt.y > pt.floor) { pt.y = pt.floor; pt.vy *= -0.35; pt.vx *= 0.7; }
                const lp = (now - pt.t0) / pt.life;
                ctx.globalAlpha = lp > 0.7 ? (1 - lp) / 0.3 : 1;
                ctx.fillStyle = pt.color;
                ctx.fillRect(pt.x | 0, pt.y | 0, pt.size, pt.size);
            }
            ctx.globalAlpha = 1;

            ctx.restore();
            st.raf = requestAnimationFrame(loop);
        };
        st.raf = requestAnimationFrame(loop);
        battles.set(canvasId, st);
    }

    function destroyBattle(canvasId) {
        const st = battles.get(canvasId);
        if (!st) return;
        cancelAnimationFrame(st.raf);
        st.ro?.disconnect();
        if (st.onDown) {
            st.canvas.removeEventListener('pointerdown', st.onDown);
            st.canvas.removeEventListener('pointermove', st.onMove);
            st.canvas.removeEventListener('pointerup', st.onUp);
            st.canvas.removeEventListener('pointercancel', st.onCancel);
            st.canvas.removeEventListener('wheel', st.onWheel);
        }
        battles.delete(canvasId);
    }

    // Swap the enemy actor in place (endless waves) with a pop-in.
    async function setBattleEnemy(canvasId, enemyId) {
        const st = battles.get(canvasId);
        if (!st) return;
        const token = ++st.enemySwapToken;
        const model = await loadModel(npcModelUrl(enemyId)).catch(() => null)
            ?? await loadModel('assets/player.vox').catch(() => null);
        const live = battles.get(canvasId);
        if (!model || !live || live.enemySwapToken !== token) return; // stale swap or destroyed
        live.enemyId = enemyId;
        live.enemy = makeActor(model, LAYOUT.enemy, npcFallbackTint(enemyId), live.rigOf(enemyId));
        live.enemy.st = live;
        live.enemy.anims.push({ type: 'spawn', t0: live.time, dur: 300 });
    }

    function setBattleFlags(canvasId, flags) {
        const st = battles.get(canvasId);
        if (!st) return;
        Object.assign(st.flags, flags);
        // Style rotation can advance the moment the NPC attacks, so the impact
        // color comes from the style that was showing during the wind-up.
        if (st.flags.windup) st.lastWindupStyle = st.flags.windup;
    }

    // HP fractions (0..1) drive voxel erosion/regrow; called every game tick.
    function setBattleVitals(canvasId, vitals) {
        const st = battles.get(canvasId);
        if (!st) return;
        for (const [actor, frac] of [[st.player, vitals.player], [st.enemy, vitals.enemy]]) {
            if (actor.crumbled || typeof frac !== 'number') continue;
            const f = Math.max(0, Math.min(1, frac));
            setActorVisible(actor, Math.round(actor.ordered.length * (0.45 + 0.55 * f)));
        }
    }

    // Equip/unequip the weapon shown in the player's hand. The weapon's
    // voxels merge into the player's render list at the rig hand anchor.
    async function setBattleWeapon(canvasId, weaponId) {
        const st = battles.get(canvasId);
        if (!st) return;
        const token = ++st.weaponToken;
        if (!weaponId || !ITEM_ASSETS.has(weaponId)) {
            st.weaponId = null;
            attachWeapon(st.player, null);
            return;
        }
        const model = await loadModel(`assets/items/${weaponId}.vox`).catch(() => null);
        const live = battles.get(canvasId);
        if (!live || live.weaponToken !== token) return; // stale or destroyed
        live.weaponId = model ? weaponId : null;
        attachWeapon(live.player, model, live.rigs?.weapons?.[weaponId]?.grip);
    }

    // Sim tile positions (from GameState). A changed tile opens a straight
    // segment from wherever the actor currently is, covered in exactly one
    // tick — a 2-tile running step just moves twice as fast, and a late
    // update re-anchors mid-stride, so motion never stalls between tiles.
    function setBattlePositions(canvasId, pos) {
        const st = battles.get(canvasId);
        if (!st) return;
        const order = (actor, x, z) => {
            if (actor.target.wx === x && actor.target.wz === z) return;
            actor.target = { wx: x, wz: z };
            actor.seg = { x0: actor.pos.wx, z0: actor.pos.wz, x1: x, z1: z, t0: st.time };
        };
        if (pos.player) order(st.player, pos.player.x, pos.player.z);
        if (pos.enemy) order(st.enemy, pos.enemy.x, pos.enemy.z);
    }

    // Restore both actors for a rematch on the same mounted scene (RETRY).
    function resetBattle(canvasId) {
        const st = battles.get(canvasId);
        if (!st) return;
        for (const actor of [st.player, st.enemy]) {
            actor.crumbled = false;
            actor.anims = [{ type: 'spawn', t0: st.time, dur: 250 }];
            actor.lastRemoved = [];
            actor.pos = { wx: actor.base.wx, wz: actor.base.wz };
            actor.target = { wx: actor.base.wx, wz: actor.base.wz };
            actor.seg = null;
            actor.facing = actor.base.facing;
            actor.moving = false;
            actor.walkPhase = 0;
            setActorVisible(actor, actor.ordered.length);
        }
        st.moveMarker = null;
        st.effects = []; st.particles = []; st.projectiles = [];
        st.pendingFreezes = []; st.cam = null; st.shake = null;
        st.freezeUntil = 0; st.slowUntil = 0;
        st.delayEnemyVis = 0; st.delayPlayerVis = 0;
    }

    // evt = { type, tier?, dmg?, style? }; types: playerAttack | enemyAttack |
    // playerHit | enemyHit | enemyDeath | playerDeath. Attack events fire
    // projectiles for ranged/magic and delay the matching hit's visuals by the
    // travel time. No-op when the battle is gone.
    function battleEvent(canvasId, evt) {
        const st = battles.get(canvasId);
        if (!st) return;
        const now = st.time;
        const dmg = evt.dmg | 0;
        const landed = evt.tier !== 'miss' && evt.tier !== 'poison';
        const big = evt.tier === 'heavy' || evt.tier === 'spec' || evt.tier === 'boss';
        const W = st.canvas.width, H = st.canvas.height;

        const attack = (attacker, defender, style, kind) => {
            attacker.anims.push({ type: 'attack', t0: now, dur: 340, kind });
            if (style === 'ranged' || style === 'magic') {
                // travel time from real distance — shots from across the
                // arena visibly take longer to arrive
                const a = torso(attacker, W, H), b = torso(defender, W, H);
                const wu = Math.hypot(defender.pos.wx - attacker.pos.wx, defender.pos.wz - attacker.pos.wz);
                const travel = Math.max(120, Math.min(420, wu / 14 * 1000));
                st.projectiles.push({ x0: a.x, y0: a.y, x1: b.x, y1: b.y, t0: now + 60, dur: travel, style });
                return 60 + travel; // defender visuals wait for the projectile
            }
            return 0;
        };
        // Attack choreography: per-weapon override, else the melee kind from
        // the event (weapon AttackType), else the NPC's signature swing.
        const playerKind =
            WEAPON_ANIMS[st.weaponId] ?? (evt.kind in ATTACK_POSES ? evt.kind : 'slash');
        const enemyKind =
            st.lastWindupStyle === 'ranged' ? 'bow' :
            st.lastWindupStyle === 'magic' ? 'cast' :
            (NPC_ANIMS[st.enemyId] ?? 'slash');
        const impact = (defender, attacker, delay, color) => {
            const t0 = now + delay;
            if (evt.tier === 'miss') { defender.anims.push({ type: 'dodge', t0, dur: 260 }); return; }
            defender.anims.push({ type: 'hit', t0, dur: 260, amp: Math.min(7, 2 + dmg * 0.35) });
            if (!landed) return; // poison DoT: flash only
            st.effects.push({ on: defender === st.player ? 'player' : 'enemy', t0, dur: 280, color });
            spawnDebris(st, defender, attacker, Math.min(4 + dmg, 14), t0, defender.lastRemoved);
            defender.lastRemoved = [];
            st.pendingFreezes.push({ at: t0, dur: big ? 95 : 60 });
            st.shake = { mag: Math.min(3, 1 + dmg * 0.15), t0, dur: 90 };
            if (big) {
                const c = torso(defender, W, H);
                st.cam = { amt: 0.10, x: c.x, y: c.y, t0, dur: 300 };
            }
        };

        switch (evt.type) {
            case 'playerAttack': st.delayEnemyVis = attack(st.player, st.enemy, evt.style, playerKind); break;
            case 'enemyAttack':  st.delayPlayerVis = attack(st.enemy, st.player, st.lastWindupStyle, enemyKind); break;
            case 'enemyHit': {
                const d = st.delayEnemyVis; st.delayEnemyVis = 0;
                impact(st.enemy, st.player, d, '#ffd76a');
                break;
            }
            case 'playerHit': {
                const d = st.delayPlayerVis; st.delayPlayerVis = 0;
                impact(st.player, st.enemy, d, STYLE_COLORS[st.lastWindupStyle] ?? '#ffffff');
                break;
            }
            case 'enemyDeath':
            case 'playerDeath': {
                st.flags.telegraph = false;
                st.flags.windup = null;
                const dying = evt.type === 'enemyDeath' ? st.enemy : st.player;
                const other = evt.type === 'enemyDeath' ? st.player : st.enemy;
                const c = torso(dying, W, H);
                crumbleActor(st, dying, other);
                st.slowUntil = performance.now() + 600;
                st.cam = { amt: 0.15, x: c.x, y: c.y, t0: now, dur: 900 };
                break;
            }
        }
    }

    window.voxel = {
        initPreview, destroyPreview, renderIcon, itemIcon,
        initBattle, destroyBattle, setBattleEnemy, setBattleFlags, battleEvent,
        setBattleVitals, setBattleWeapon, setBattlePositions, resetBattle,
    };
})();
